version: "3"
services:
  find-university:
    container_name: find-university
    image: harbor.croz.net/docker/library/postgres:13.2
    environment:
      POSTGRES_DB: university1
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
